# Generated by Django 2.1 on 2020-02-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationAndPrize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_object_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
