# Generated by Django 2.1 on 2020-03-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationAndPrize', '0002_notification_extra_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
