# Generated by Django 2.1 on 2020-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationAndPrize', '0003_notification_notification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='app_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='model_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('2DA', '2 рет қатарынан сабаққа келмеді'), ('RRQ', 'Пересдачадан құлады'), ('NHW', 'Үй жұмысы жоқ'), ('3UTT', '3 рет баллын көтерді'), ('MTT', 'Пробный тесттен макс. жинады'), ('MQ', 'Аралық бақылаудан макс. жинады'), ('EQ', 'Аралық бақылауды жақсы жазды')], max_length=10),
        ),
    ]
