# Generated by Django 2.1 on 2020-03-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationAndPrize', '0004_auto_20200306_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='app_name',
            new_name='extra_object_app_name',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='model_name',
            new_name='extra_object_model_name',
        ),
        migrations.AddField(
            model_name='notification',
            name='object_app_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='object_model_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
