# Generated by Django 2.1 on 2020-01-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvisit',
            name='no_home_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentvisithistory',
            name='no_home_work',
            field=models.BooleanField(default=False),
        ),
    ]
