# Generated by Django 2.1 on 2020-01-24 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0002_auto_20200124_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudentvisit',
            name='abs_date',
            field=models.DateField(default=datetime.date(2020, 1, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupstudentvisithistory',
            name='abs_date',
            field=models.DateField(default=datetime.date(2020, 1, 24)),
            preserve_default=False,
        ),
    ]
