# Generated by Django 2.1 on 2020-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0003_auto_20200124_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudentvisithistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentvisithistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
