# Generated by Django 2.1 on 2020-01-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0004_auto_20200124_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvisit',
            name='lesson_group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_group_student', to='groupsAndLessons.LessonGroupStudent'),
        ),
    ]
