# Generated by Django 2.1 on 2020-01-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0005_auto_20200124_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvisit',
            name='group_student_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_student_visit', to='lessonProgress.GroupStudentVisit'),
        ),
    ]
