# Generated by Django 2.1 on 2020-01-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0006_auto_20200129_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvisit',
            name='lesson_group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_group_student', to='groupsAndLessons.LessonGroupStudent'),
        ),
    ]
