# Generated by Django 2.1 on 2020-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0008_auto_20200131_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquizmark',
            name='practice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicquizmark',
            name='theory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicquizmarkhistory',
            name='practice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicquizmarkhistory',
            name='theory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
