# Generated by Django 2.1 on 2020-02-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0042_auto_20200207_1929'),
        ('lessonProgress', '0009_auto_20200207_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicquizmarkhistory',
            old_name='student_plan_id',
            new_name='topic_plan_id',
        ),
        migrations.RemoveField(
            model_name='topicquizmark',
            name='student_plan',
        ),
        migrations.AddField(
            model_name='topicquizmark',
            name='topic_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tqm_topic_plan', to='groupsAndLessons.TopicPlan'),
            preserve_default=False,
        ),
    ]
