# Generated by Django 2.1 on 2020-02-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0010_auto_20200207_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicquizmarkhistory',
            old_name='teacher_id',
            new_name='changed_user_id',
        ),
        migrations.RemoveField(
            model_name='topicquizmark',
            name='teacher',
        ),
    ]
