# Generated by Django 2.1 on 2020-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0011_auto_20200207_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquizmarkhistory',
            name='origin_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
