# Generated by Django 2.1 on 2020-02-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0012_topicquizmarkhistory_origin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialTestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('student_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('updated_date', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.RemoveField(
            model_name='trialtestmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trialtestmarkhistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='trialtestmarkhistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trialtestmark',
            name='trial_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonProgress.TrialTest'),
        ),
    ]
