# Generated by Django 2.1 on 2020-02-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0013_auto_20200220_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialtestmark',
            name='trial_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ttm_trial_test', to='lessonProgress.TrialTest'),
        ),
    ]
