# Generated by Django 2.1 on 2020-02-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0014_auto_20200221_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trialtesthistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='trialtesthistory',
            name='updated_date',
        ),
    ]
