# Generated by Django 2.1 on 2020-02-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0015_auto_20200221_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trialtesthistory',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AddField(
            model_name='trialtesthistory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
