# Generated by Django 2.1 on 2020-02-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0016_auto_20200221_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudentvisit',
            name='lesson_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lg_group_student_visit', to='groupsAndLessons.LessonGroup'),
        ),
    ]
