# Generated by Django 2.1 on 2020-02-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0018_auto_20200224_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonvideoactionhistory',
            old_name='lesson_group_student',
            new_name='lesson_group_student_id',
        ),
    ]
