# Generated by Django 2.1 on 2020-02-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0019_auto_20200225_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontestaction',
            name='lesson_group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgs_lesson_test_action', to='groupsAndLessons.LessonGroupStudent'),
        ),
        migrations.AlterField(
            model_name='lessonvideoaction',
            name='lesson_group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgs_lesson_video_action', to='groupsAndLessons.LessonGroupStudent'),
        ),
        migrations.AlterField(
            model_name='studentvisit',
            name='lesson_group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgs_student_visit', to='groupsAndLessons.LessonGroupStudent'),
        ),
    ]
