# Generated by Django 2.1 on 2020-03-10 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessonProgress', '0020_auto_20200227_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquizmark',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicquizmarkhistory',
            name='student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
