# Generated by Django 2.1 on 2020-03-10 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0021_auto_20200310_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquizmark',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
