# Generated by Django 2.1 on 2020-03-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0022_auto_20200310_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicquizmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='topicquizmarkhistory',
            name='student_id',
        ),
    ]
