# Generated by Django 2.1 on 2020-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0026_auto_20200310_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquizmark',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
