# Generated by Django 2.1 on 2020-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0029_auto_20200312_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialtestmark',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
