# Generated by Django 2.1 on 2020-03-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonProgress', '0030_auto_20200312_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquizmark',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
