# Generated by Django 2.1 on 2019-11-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatushistory',
            old_name='user_id',
            new_name='changed_user_id',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
    ]
