# Generated by Django 2.1 on 2019-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_auto_20191129_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatushistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
