# Generated by Django 2.1 on 2019-12-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_auto_20191129_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupstatushistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='groupstatushistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
