# Generated by Django 2.1 on 2019-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecthistory',
            old_name='user_id',
            new_name='created_user_id',
        ),
        migrations.RenameField(
            model_name='topichistory',
            old_name='user_id',
            new_name='created_user_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.AddField(
            model_name='videohistory',
            name='created_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='videohistory',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
