# Generated by Django 2.1 on 2020-02-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20191207_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t_video', to='materials.Topic'),
        ),
    ]
