# Generated by Django 2.1 on 2020-03-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20200224_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videohistory',
            name='created_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
