# Generated by Django 2.1 on 2019-11-08 10:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('student_limit', models.IntegerField()),
                ('send_message_on_no_payment', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('group_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.GroupStatus')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonGroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('group_status_id', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('student_limit', models.IntegerField()),
                ('send_message_on_no_payment', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonGroupStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('lesson_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.LessonGroup')),
                ('lesson_group_student_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.LessonGroupStudentStatus')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonGroupStudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('student_plan_id', models.IntegerField()),
                ('lesson_group_id', models.IntegerField()),
                ('lesson_group_student_status_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_ipv4', models.CharField(max_length=15)),
                ('accessed_ipv6', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('lesson_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.LessonGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'lesson_group'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccessInfoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('lesson_group_id', models.IntegerField()),
                ('accessed_ipv4', models.CharField(max_length=15)),
                ('accessed_ipv6', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('lesson_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.LessonGroup')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.Office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_num', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('office_id', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'progress'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('plan_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.AddField(
            model_name='lessongroupstudent',
            name='student_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.StudentPlan'),
        ),
        migrations.AddField(
            model_name='lessongroupstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
