# Generated by Django 2.1 on 2019-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0002_auto_20191108_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplan',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentplanhistory',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
