# Generated by Django 2.1 on 2019-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0004_auto_20191127_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicplan',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topicplanhistory',
            name='order',
            field=models.IntegerField(),
        ),
    ]
