# Generated by Django 2.1 on 2019-11-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0005_auto_20191127_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicplan',
            name='student_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_topic_plan', to='groupsAndLessons.StudentPlan'),
        ),
    ]
