# Generated by Django 2.1 on 2019-12-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20191207_1413'),
        ('groupsAndLessons', '0007_auto_20191207_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentplan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studentplanhistory',
            name='title',
        ),
        migrations.AddField(
            model_name='studentplan',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='materials.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentplanhistory',
            name='subject_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
