# Generated by Django 2.1 on 2019-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0008_auto_20191207_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicplan',
            old_name='order',
            new_name='subject_order',
        ),
        migrations.RenameField(
            model_name='topicplanhistory',
            old_name='order',
            new_name='subject_order',
        ),
        migrations.RemoveField(
            model_name='topicplan',
            name='topic_progress',
        ),
        migrations.RemoveField(
            model_name='topicplanhistory',
            name='topic_progress',
        ),
        migrations.AddField(
            model_name='topicplan',
            name='class_work',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='topicplan',
            name='home_work',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='topicplan',
            name='tutorial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='topicplanhistory',
            name='class_work',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='topicplanhistory',
            name='home_work',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='topicplanhistory',
            name='tutorial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
