# Generated by Django 2.1 on 2019-12-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20191207_1413'),
        ('groupsAndLessons', '0009_auto_20191207_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('student_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_plan', to='groupsAndLessons.StudentPlan')),
                ('subject', models.ForeignKey(on_delete=models.Model, to='materials.Subject')),
            ],
            options={
                'ordering': ['-student_plan'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPlanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField()),
                ('student_plan_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='topicplan',
            options={'ordering': ['subject_plan']},
        ),
        migrations.RenameField(
            model_name='topicplanhistory',
            old_name='student_plan_id',
            new_name='subject_plan_id',
        ),
        migrations.RemoveField(
            model_name='topicplan',
            name='student_plan',
        ),
        migrations.RemoveField(
            model_name='topicplan',
            name='subject_order',
        ),
        migrations.RemoveField(
            model_name='topicplanhistory',
            name='subject_order',
        ),
        migrations.AddField(
            model_name='topicplan',
            name='subject_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.SubjectPlan'),
            preserve_default=False,
        ),
    ]
