# Generated by Django 2.1 on 2019-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0011_auto_20191211_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicplan',
            name='class_work',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='topicplan',
            name='home_work',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='topicplan',
            name='tutorial',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='topicplanhistory',
            name='class_work',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='topicplanhistory',
            name='home_work',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='topicplanhistory',
            name='tutorial',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
