# Generated by Django 2.1 on 2019-12-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0013_auto_20191211_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicplan',
            name='subject_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_plan', to='groupsAndLessons.SubjectPlan'),
        ),
    ]
