# Generated by Django 2.1 on 2019-12-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0014_auto_20191211_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officehistory',
            old_name='user_id',
            new_name='changed_user_id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='user',
        ),
    ]
