# Generated by Django 2.1 on 2019-12-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0015_auto_20191224_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulehistory',
            old_name='user_id',
            new_name='changed_user_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
