# Generated by Django 2.1 on 2019-12-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0017_auto_20191224_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_group',
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.Schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessongrouphistory',
            name='schedule_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
