# Generated by Django 2.1 on 2019-12-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0019_auto_20191224_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('office', 'start_time', 'finish_time', 'week_num')},
        ),
    ]
