# Generated by Django 2.1 on 2019-12-26 10:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0021_auto_20191225_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessongrouphistory',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='lessongrouphistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessongrouphistory',
            name='schedule_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=6),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='schedule',
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='schedule',
            field=models.ManyToManyField(to='groupsAndLessons.Schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_num',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')]),
        ),
    ]
