# Generated by Django 2.1 on 2019-12-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0022_auto_20191226_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessongroup',
            old_name='schedule',
            new_name='schedules',
        ),
    ]
