# Generated by Django 2.1 on 2019-12-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0023_auto_20191226_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessongroup',
            name='schedules',
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='schedule',
            field=models.ManyToManyField(related_name='schedules', to='groupsAndLessons.Schedule'),
        ),
    ]
