# Generated by Django 2.1 on 2019-12-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0025_auto_20191226_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroupschedule',
            name='lesson_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='groupsAndLessons.LessonGroup'),
        ),
        migrations.AlterField(
            model_name='lessongroupschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='groupsAndLessons.Schedule'),
        ),
    ]
