# Generated by Django 2.1 on 2019-12-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0027_auto_20191226_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessongroupstudent',
            name='lesson_group_student_status',
        ),
        migrations.RemoveField(
            model_name='lessongroupstudenthistory',
            name='lesson_group_student_status_id',
        ),
    ]
