# Generated by Django 2.1 on 2019-12-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0028_auto_20191230_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessongroupstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lessongroupstudenthistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='lessongroupstudenthistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
