# Generated by Django 2.1 on 2019-12-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0029_auto_20191230_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessongroupstudenthistory',
            old_name='schedule_id',
            new_name='lesson_group_id',
        ),
        migrations.RemoveField(
            model_name='lessongroupstudent',
            name='schedule',
        ),
        migrations.AddField(
            model_name='lessongroupstudent',
            name='lesson_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.LessonGroup'),
            preserve_default=False,
        ),
    ]
