# Generated by Django 2.1 on 2020-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0032_auto_20200109_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
