# Generated by Django 2.1 on 2020-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0033_auto_20200118_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroupstudent',
            name='started_date',
            field=models.DateTimeField(),
        ),
    ]
