# Generated by Django 2.1 on 2020-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0034_auto_20200122_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroupstudent',
            name='started_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lessongroupstudenthistory',
            name='started_date',
            field=models.DateField(),
        ),
    ]
