# Generated by Django 2.1 on 2020-01-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0035_auto_20200122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicplanhistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
