# Generated by Django 2.1 on 2020-02-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0027_auto_20200118_2021'),
        ('groupsAndLessons', '0036_auto_20200131_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('lesson_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsAndLessons.LessonGroup')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userInfo.Staff')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupReplacementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('lesson_group_id', models.IntegerField()),
                ('teacher_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.RemoveField(
            model_name='materialaccessinfohistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='materialaccessinfohistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
