# Generated by Django 2.1 on 2020-02-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0038_auto_20200201_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupreplacement',
            name='lesson_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gr_lesson_group', to='groupsAndLessons.LessonGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupreplacement',
            unique_together={('lesson_group', 'date')},
        ),
    ]
