# Generated by Django 2.1 on 2020-02-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0039_auto_20200204_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGroupStudentShortSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day_sign', models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ'), (7, 'ВС')])),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('lesson_group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsAndLessons.LessonGroupStudent')),
            ],
        ),
        migrations.CreateModel(
            name='LessonGroupStudentShortScheduleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('lesson_group_student_id', models.IntegerField()),
                ('week_day_sign', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
