# Generated by Django 2.1 on 2020-02-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0040_lessongroupstudentshortschedule_lessongroupstudentshortschedulehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroupstudentshortschedule',
            name='lesson_group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_schedule', to='groupsAndLessons.LessonGroupStudent'),
        ),
    ]
