# Generated by Django 2.1 on 2020-02-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0041_auto_20200205_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicplan',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tp_topic', to='materials.Topic'),
        ),
    ]
