# Generated by Django 2.1 on 2020-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0043_auto_20200211_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
