# Generated by Django 2.1 on 2020-02-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0044_auto_20200211_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTimeTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('lesson_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsAndLessons.LessonGroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTimeTransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('lesson_group_id', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='grouptimetransfer',
            unique_together={('lesson_group', 'from_date')},
        ),
    ]
