# Generated by Django 2.1 on 2020-02-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0045_auto_20200211_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptimetransfer',
            name='to_date',
            field=models.DateField(),
        ),
    ]
