# Generated by Django 2.1 on 2020-02-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0046_auto_20200212_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialaccessinfo',
            options={'ordering': ['lesson_group']},
        ),
        migrations.RemoveField(
            model_name='materialaccessinfo',
            name='user',
        ),
    ]
