# Generated by Django 2.1 on 2020-02-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0050_auto_20200222_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupschedule',
            name='lesson_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lg_group_schedule', to='groupsAndLessons.LessonGroup'),
        ),
    ]
