# Generated by Django 2.1 on 2020-02-27 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0052_auto_20200226_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroupstudent',
            name='student_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sp_lesson_group_student', to='groupsAndLessons.StudentPlan'),
        ),
        migrations.AlterField(
            model_name='studentplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='s_student_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
