# Generated by Django 2.1 on 2019-11-08 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('grade', models.IntegerField()),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7999999999), django.core.validators.MinValueValidator(7000000000)])),
                ('red_medal', models.BooleanField(default=False)),
                ('gold_medal', models.BooleanField(default=False)),
                ('dob', models.DateTimeField()),
                ('school', models.CharField(max_length=120)),
                ('home_phone', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=120)),
                ('target_subject', models.CharField(max_length=120)),
                ('target_from', models.CharField(max_length=120)),
                ('instagram', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.UserStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('grade', models.IntegerField()),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7999999999), django.core.validators.MinValueValidator(7000000000)])),
                ('red_medal', models.BooleanField(default=False)),
                ('gold_medal', models.BooleanField(default=False)),
                ('dob', models.DateTimeField()),
                ('school', models.CharField(max_length=120)),
                ('home_phone', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('target_subject', models.CharField(max_length=120)),
                ('target_from', models.CharField(max_length=120)),
                ('instagram', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('SM', 'Super Moderator'), ('M', 'Moderator'), ('S', 'Student'), ('T', 'Teacher'), ('SY', 'System')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
