# Generated by Django 2.1 on 2019-11-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0001_initial'),
        ('userInfo', '0002_auto_20191108_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='groupsAndLessons.Schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='schedule_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='status_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
