# Generated by Django 2.1 on 2019-11-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_auto_20191108_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='schedule_id',
        ),
    ]
