# Generated by Django 2.1 on 2019-11-13 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0004_auto_20191108_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('SM', 'Super Moderator'), ('M', 'Moderator'), ('S', 'Student'), ('T', 'Teacher'), ('SY', 'System'), ('D', 'Developer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
