# Generated by Django 2.1 on 2019-11-23 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0008_auto_20191122_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
