# Generated by Django 2.1 on 2019-11-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0010_auto_20191123_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='home_phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='target_from',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='target_subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
