# Generated by Django 2.1 on 2019-11-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0012_auto_20191123_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('SM', 'Super Moderator'), ('M', 'Moderator'), ('S', 'Student'), ('T', 'Teacher'), ('SY', 'System'), ('D', 'Developer'), ('P', 'Parent')], max_length=2),
        ),
    ]
