# Generated by Django 2.1 on 2019-11-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0013_auto_20191123_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='home_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statuses.UserStatus'),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
