# Generated by Django 2.1 on 2019-11-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0014_auto_20191123_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
