# Generated by Django 2.1 on 2019-11-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0015_auto_20191123_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='changed_user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
