# Generated by Django 2.1 on 2019-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0016_studenthistory_changed_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
