# Generated by Django 2.1 on 2019-11-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0017_auto_20191129_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='status_id',
        ),
        migrations.AddField(
            model_name='student',
            name='force_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_password_reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='force_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='has_contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='has_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='is_password_reset',
            field=models.BooleanField(default=True),
        ),
    ]
