# Generated by Django 2.1 on 2019-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0018_auto_20191129_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenthistory',
            name='changed_user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
