# Generated by Django 2.1 on 2019-12-04 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0019_parenthistory_changed_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7999999999), django.core.validators.MinValueValidator(7000000000)]),
        ),
    ]
