# Generated by Django 2.1 on 2019-12-04 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0020_auto_20191204_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenthistory',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7999999999), django.core.validators.MinValueValidator(7000000000)]),
        ),
    ]
