# Generated by Django 2.1 on 2019-12-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0022_teacher_teacherhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacherhistory',
            name='phone',
        ),
    ]
