# Generated by Django 2.1 on 2019-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0024_auto_20191219_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('role', models.CharField(max_length=2)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
    ]
