# Generated by Django 2.1 on 2020-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0025_userrolehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolehistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
