# Generated by Django 2.1 on 2020-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0026_auto_20200116_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenthistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
