# Generated by Django 2.1 on 2020-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0030_studentfreeze_studentfreezehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfreeze',
            name='comment',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfreezehistory',
            name='comment',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
