# Generated by Django 2.1 on 2020-03-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsAndLessons', '0053_auto_20200227_1829'),
        ('userInfo', '0031_auto_20200227_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupFreeze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=120)),
                ('lesson_group_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgs_student_group_freeze', to='groupsAndLessons.LessonGroupStudent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroupFreezeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('lesson_group_student_id', models.IntegerField()),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=120)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
    ]
