# Generated by Django 2.1 on 2020-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200218_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercategoryhistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersalarycategoryhistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersalarycoefficienthistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
