# Generated by Django 2.1 on 2020-02-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0027_auto_20200118_2021'),
        ('payment', '0003_auto_20200219_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachercategory',
            unique_together={('teacher_salary_category', 'teacher')},
        ),
    ]
