# Generated by Django 2.1 on 2020-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200219_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercategoryhistory',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AddField(
            model_name='teachercategoryhistory',
            name='teacher_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
