# Generated by Django 2.1 on 2020-02-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200219_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercategoryhistory',
            name='teacher_salary_category_id',
        ),
        migrations.RemoveField(
            model_name='teachersalarycategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='teachersalarycategoryhistory',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='teachercategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teachercategory',
            name='teacher_salary_category',
        ),
    ]
