# Generated by Django 2.1 on 2020-02-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0027_auto_20200118_2021'),
        ('payment', '0006_auto_20200219_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalaryCategoryLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSalaryCategoryLevelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.AddField(
            model_name='teachercategoryhistory',
            name='teacher_salary_category_level_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachersalarycategoryhistory',
            name='teacher_salary_category_level_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercategory',
            name='teacher_salary_category_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment.TeacherSalaryCategoryLevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachersalarycategory',
            name='teacher_salary_category_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment.TeacherSalaryCategoryLevel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teachercategory',
            unique_together={('teacher_salary_category_level', 'teacher')},
        ),
    ]
