# Generated by Django 2.1 on 2020-02-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200219_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercategory',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Staff', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='teachercategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teachersalarycategory',
            unique_together={('teacher_salary_category_level', 'lessons_per_week')},
        ),
    ]
