# Generated by Django 2.1 on 2020-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20200206_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessongroupipconfiguration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lessongroupipconfigurationhistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='lessongroupipconfigurationhistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessongroupipconfigurationhistory',
            name='is_checking_ip',
            field=models.BooleanField(default=True),
        ),
    ]
