# Generated by Django 2.1 on 2020-02-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20200224_1950'),
        ('configuration', '0003_auto_20200226_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectQuizMarkConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retake_mark', models.IntegerField()),
                ('excellent_mark', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectQuizMarkConfigurationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField()),
                ('retake_mark', models.IntegerField()),
                ('excellent_mark', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.RemoveField(
            model_name='trialtestmaxmarkconfiguration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trialtestmaxmarkconfigurationhistory',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='trialtestminmarkconfiguration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trialtestminmarkconfigurationhistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='trialtestmaxmarkconfigurationhistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialtestminmarkconfigurationhistory',
            name='changed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
