# Generated by Django 2.1 on 2020-02-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20200224_1950'),
        ('configuration', '0004_auto_20200229_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialTestMarkConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_mark', models.IntegerField()),
                ('min_mark', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Subject')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='TrialTestMarkConfigurationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('changed_user_id', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField()),
                ('max_mark', models.IntegerField()),
                ('min_mark', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.RemoveField(
            model_name='trialtestmaxmarkconfiguration',
            name='subject',
        ),
        migrations.DeleteModel(
            name='TrialTestMaxMarkConfigurationHistory',
        ),
        migrations.RemoveField(
            model_name='trialtestminmarkconfiguration',
            name='subject',
        ),
        migrations.DeleteModel(
            name='TrialTestMinMarkConfigurationHistory',
        ),
        migrations.DeleteModel(
            name='TrialTestMaxMarkConfiguration',
        ),
        migrations.DeleteModel(
            name='TrialTestMinMarkConfiguration',
        ),
    ]
