# Generated by Django 2.1 on 2020-03-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20200229_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroupipconfiguration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessongroupipconfigurationhistory',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subjectquizconfiguration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subjectquizconfigurationhistory',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subjectquizmarkconfiguration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subjectquizmarkconfigurationhistory',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trialtestmarkconfiguration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trialtestmarkconfigurationhistory',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
