from django.urls import path
from .views import (
    StudentPlanDetailView,
    OfficeListView,
    OfficeDetailView,
    ScheduleListView,
    # SetDefaultSchedules,
    LessonGroupDetailView,
    LessonGroupListView, #depreciated
    LessonGroupListOffsetView,
    LessonGroupStudentDetailView,
    LessonGroupStudentListView,
    LessonGroupListByTeacherView,
    AvailableScheduleListView,
    StudentPlanByPkDetailView,
    GroupReplaceListView,
    GroupReplacementDetailView,
    DayOffListView,
    DayOffDetailView,
    GroupTimeTransferListView,
    GroupTimeTransferDetailView,
    UpdateGroupListView,
    ResetMaterialAccessView

    # MigrateStudentProgress,
    # SetStudentsShortSchedules,
    # SetUnsettedTopicPlanView,
    # DeleteIncorrectTopicPlanView,
)

urlpatterns = [
    path('set/plan/student/', StudentPlanDetailView.as_view()),
    path('edit/plan/student/<student_plan_pk>/', StudentPlanDetailView.as_view()),
    path('plan/<student_pk>/', StudentPlanDetailView.as_view()),
    path('student/plan/<student_plan_pk>/', StudentPlanByPkDetailView.as_view()),
    path('office/', OfficeDetailView.as_view()),
    path('office/list/', OfficeListView.as_view()),
    path('schedule/list/', ScheduleListView.as_view()),
    path('group/create/', LessonGroupDetailView.as_view()),
    path('group/edit/<lesson_group_pk>/', LessonGroupDetailView.as_view()),
    path('group/delete/<lesson_group_pk>/', LessonGroupDetailView.as_view()),
    path('group/list/', LessonGroupListView.as_view()), #depreciiated
    path('group/list/<start>/<limit>/', LessonGroupListOffsetView.as_view()),
    path('group/list/teacher/', LessonGroupListByTeacherView.as_view()),
    path('add/plan/', LessonGroupStudentDetailView.as_view()),
    path('edit/plan/group/<lesson_group_student_pk>/', LessonGroupStudentDetailView.as_view()),
    path('remove/plan/group/<group_student_pk>/', LessonGroupStudentDetailView.as_view()),
    path('plan/list/<lesson_group_pk>/', LessonGroupStudentListView.as_view()),
    path('schedule/list/available/', AvailableScheduleListView.as_view()),
    path('replace/list/<group_pk>/', GroupReplaceListView.as_view()),
    path('replace/', GroupReplacementDetailView.as_view()),
    path('replace/<group_replacement_pk>/', GroupReplacementDetailView.as_view()),
    path('dayoff/list/', DayOffListView.as_view()),
    path('dayoff/set/', DayOffDetailView.as_view()),
    path('dayoff/edit/<day_off>/', DayOffDetailView.as_view()),
    path('dayoff/delete/<day_off>/', DayOffDetailView.as_view()),
    path('group/time/transfer/list/<lesson_group_pk>/', GroupTimeTransferListView.as_view()),
    path('group/time/transfer/set/', GroupTimeTransferDetailView.as_view()),
    path('group/time/transfer/delete/<group_time_transfer_pk>/', GroupTimeTransferDetailView.as_view()),
    path('update/group/list/', UpdateGroupListView.as_view()),
    path('reset/group/ip/', ResetMaterialAccessView.as_view()),
    # path('schedule/set/default/', SetDefaultSchedules.as_view())
    # path('token/', AuthView.as_view()),

    # path('migrate/student/progress/', MigrateStudentProgress.as_view()),
    # path('set/student/short/schedule/', SetStudentsShortSchedules.as_view()),
    # path('set/unsetted/quizes/', SetUnsettedTopicPlanView.as_view()),
    # path('delete/incorrect/quizes/', DeleteIncorrectTopicPlanView.as_view()),
]
